source 'https://rubygems.org'

# Web framework
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'rackup'

# HTML parsers
gem 'nokogiri'
gem 'oga'

# HTTP client (goi PHP service)
gem 'httparty'

# JSON
gem 'json'
